name = "boop-blog-worker"
compatibility_date = "2025-09-03"
enableRobotsTXT = true

[build]
command = "chmod a+x build.sh && ./build.sh"

[assets]
directory = "./public"
not_found_handling = "404-page"

[[routes]]
pattern = "boop.fyi"
custom_domain = true
